# Generated by Django 3.2 on 2022-05-25 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a job title', max_length=100)),
                ('description', models.TextField(help_text='Enter a brief description of the job')),
                ('location', models.CharField(help_text='Enter the location of the job', max_length=100)),
                ('type', models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time'), ('3', 'Contract'), ('4', 'Internship')], help_text='Select the job type', max_length=1)),
                ('category', models.CharField(help_text='Enter the category of the job', max_length=100)),
                ('last_date', models.DateField(help_text='Enter the last date of the job')),
                ('name_company', models.CharField(help_text='Enter the name of the company', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled', models.BooleanField(default=False)),
                ('salary', models.IntegerField(blank=True, help_text='Enter the salary of the job', null=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.SmallIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
